name: Publish 🎉

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./ContentManagementSystem/ContentManagementSystem.sln

    - name: Build
      run: dotnet build ./ContentManagementSystem/ContentManagementSystem.sln --configuration Release

    - name: Publish
      run: dotnet publish ./ContentManagementSystem/src/CMS.API/CMS.API.csproj --configuration Release --no-build --output './publish'

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: conent-managment-api
        publish-profile: ${{ secrets.AZURE_PUBLISH_CMS }}
        package: './publish'
